### ISSUE TITLE
Missing container

### ISSUE THREAD

**Issue by rickyzhang82** [networkop/k8s-guide-labs#2]
[The doc](https://k8s.networkop.co.uk/services/clusterip/dataplane/iptables/) invoked a command from an unknown container:

```
$ docker exec k8s-guide-worker curl -s 10.96.94.225 | grep Welcome
<title>Welcome to nginx!</title>
<h1>Welcome to nginx!</h1>
```

Where does that come from?

**Comment by networkop** [comment]
This command executes `curl -s 10.96.94.225` from inside `k8s-guide-worker` which is one of the k8s nodes. In a production k8s cluster, this would be equivalent to ssh'ing into one of the k8s nodes and running `curl -s 10.96.94.225`  from inside it.

**Comment by rickyzhang82** [comment]
I think I will just launch a busybox pod to get it done.
