### ISSUE TITLE
kind cluster gettting created with single node

### ISSUE THREAD

**Issue by bhiravabhatla** [networkop/k8s-guide-labs#5]
I see lot of examples expect 2 worker nodes for the cluster. e.g (k8s-guide-worker).

But the setup creates a single node cluster.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/36130219/220884585-434e4459-fcce-4eeb-8be0-c88fdc9e7a5e.png">

Also dont see nodes config in kind.yaml

<img width="792" alt="image" src="https://user-images.githubusercontent.com/36130219/220884892-de50a5d8-63fd-43bd-97c2-d1c2b422c9ca.png">

Am I missing something?

**Comment by networkop** [comment]
yep, looks like a bug I accidentally introduced in https://github.com/networkop/k8s-guide-labs/commit/2ba9639a3f1ebd3e990927dc5022f274884a8d8f

will fix it in a sec

**Comment by networkop** [comment]
fixed in https://github.com/networkop/k8s-guide-labs/commit/4b30380a6fc238479bb53bdee0710901c584e44d

**Comment by bhiravabhatla** [comment]
Thanks @networkop
